sudo: false

node_js:
  - "6"

cache:
  directories:
    - tests/elm-stuff/build-artifacts

install:
  - npm install -g elm@$17.1.0 elm-test
  - npm install
  - git clone https://github.com/NoRedInk/elm-ops-tooling
  - elm-ops-tooling/with_retry.rb elm package install --yes

script:
  - elm-test
