sudo: false

language: node_js

node_js:
  - "6"

cache:
  directories:
    - tests/elm-stuff/build-artifacts

install:
  - npm install -g elm@~0.18.0
  - npm install -g elm-test@0.18.2
  - npm install

script:
  - "elm-test --verbose"
